import { useState } from "react";
import { Link } from "react-router-dom";
import { Download, ChevronDown, ChevronUp, XCircle, Printer, FileSpreadsheet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Progress } from "@/components/ui/progress";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { TeamBadge } from "@/components/shared/TeamBadge";
import { ConfirmDialog } from "@/components/shared/ConfirmDialog";
import { getBatchCodes, signBatchExport, type CodeBatch } from "@/lib/api/mpromo";
import type { PromoCode } from "@/types/mpromo";
import { toast } from "sonner";

function BatchCodeTable({ codes, canCancel, onCancel }: { codes: PromoCode[]; canCancel: boolean; onCancel: (code: PromoCode) => void }) {
  return (
    <div className="border rounded-md overflow-hidden mt-3">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-muted/50 text-left">
            <th className="px-3 py-2 font-medium">Code</th>
            <th className="px-3 py-2 font-medium">Status</th>
            <th className="px-3 py-2 font-medium">Issued To</th>
            <th className="px-3 py-2 font-medium">Redeemed At</th>
            {canCancel && <th className="px-3 py-2 w-10" />}
          </tr>
        </thead>
        <tbody>
          {codes.map((c) => (
            <tr key={c.id} className="border-t">
              <td className="px-3 py-2"><code className="text-xs font-mono bg-muted px-1.5 py-0.5 rounded">{c.code}</code></td>
              <td className="px-3 py-2"><StatusBadge status={c.status} /></td>
              <td className="px-3 py-2 text-muted-foreground">{c.issued_to || "—"}</td>
              <td className="px-3 py-2 text-muted-foreground">{c.redeemed_at || "—"}</td>
              {canCancel && (
                <td className="px-3 py-2">
                  {c.status === "active" && (
                    <Button variant="ghost" size="sm" className="h-8 w-8 p-0" onClick={() => onCancel(c)}>
                      <XCircle className="h-4 w-4 text-destructive" />
                    </Button>
                  )}
                </td>
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function exportBatchPDF(batch: CodeBatch) {
  const codes = batch.codes || [];
  const win = window.open("", "_blank");
  if (!win) { toast.error("Popup blocked — please allow popups"); return; }

  const couponsHtml = codes.map((c) => `
    <div class="coupon">
      <div class="logo">Mobile Water</div>
      <div class="campaign">${batch.campaign_name}</div>
      <div class="code">${c.code}</div>
      <div class="amount">Reward: GH₵${batch.redemption_amount.toLocaleString()}</div>
      <div class="expiry">Valid until ${batch.expires_at}</div>
      <div class="instruction">Dial *920*7# to redeem</div>
      <div class="batch-ref">Batch #${batch.id}</div>
    </div>
  `).join("");

  win.document.write(`<!DOCTYPE html><html><head><title>Batch #${batch.id} Coupons</title>
<style>
  @page { size: A4; margin: 10mm; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0; }
  .coupon {
    border: 1.5px dashed #888; padding: 14px 16px;
    width: 100%; height: calc((297mm - 20mm) / 4);
    display: flex; flex-direction: column; justify-content: center; align-items: center;
    page-break-inside: avoid; text-align: center;
  }
  .logo { font-size: 16px; font-weight: 800; color: #0066cc; letter-spacing: 1px; margin-bottom: 4px; }
  .campaign { font-size: 11px; color: #555; margin-bottom: 8px; }
  .code { font-family: 'Courier New', monospace; font-size: 22px; font-weight: 700; letter-spacing: 2px; margin-bottom: 8px; }
  .amount { font-size: 14px; font-weight: 600; margin-bottom: 2px; }
  .expiry { font-size: 11px; color: #555; margin-bottom: 6px; }
  .instruction { font-size: 10px; color: #777; font-style: italic; margin-bottom: 4px; }
  .batch-ref { font-size: 9px; color: #aaa; }
</style></head><body>
<div class="grid">${couponsHtml}</div>
<script>window.onload=function(){window.print();}<\/script>
</body></html>`);
  win.document.close();
}

export function exportBatchCSV(batch: CodeBatch) {
  const codes = batch.codes || [];
  const header = "Batch ID,Campaign,Code,Status,Redemption Amount (GH₵),Expires At,Generated By,Generated At";
  const rows = codes.map((c) =>
    `${batch.id},"${batch.campaign_name}","${c.code}",${c.status},${batch.redemption_amount},"${batch.expires_at}","${batch.generated_by_name}","${batch.created_at}"`
  );
  const csv = [header, ...rows].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `batch-${batch.id}-codes.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

interface BatchCardProps {
  batch: CodeBatch;
  scopeMode?: string;
  canCancel?: boolean;
  /** Hide campaign name (useful when showing batches within a campaign detail) */
  hideCampaignName?: boolean;
}

export function BatchCard({ batch, scopeMode = "current", canCancel = false, hideCampaignName = false }: BatchCardProps) {
  const [expanded, setExpanded] = useState(false);
  const [visibleCodes, setVisibleCodes] = useState<PromoCode[]>([]);
  const [codesPage, setCodesPage] = useState(1);
  const [codesTotal, setCodesTotal] = useState(0);
  const [codesLastPage, setCodesLastPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const [confirmCode, setConfirmCode] = useState<PromoCode | null>(null);

  const handleToggle = async () => {
    if (expanded) { setExpanded(false); return; }
    if (visibleCodes.length === 0) {
      setLoading(true);
      try {
        const res = await getBatchCodes(batch.id, { page: 1, page_size: 20 });
        setVisibleCodes(res.data);
        setCodesTotal(res.total);
        setCodesLastPage(res.last_page);
        setCodesPage(1);
      } catch { toast.error("Failed to load codes"); }
      finally { setLoading(false); }
    }
    setExpanded(true);
  };

  const handleLoadMore = async () => {
    const nextPage = codesPage + 1;
    setLoading(true);
    try {
      const res = await getBatchCodes(batch.id, { page: nextPage, page_size: 20 });
      setVisibleCodes((prev) => [...prev, ...res.data]);
      setCodesPage(nextPage);
    } catch { toast.error("Failed to load more codes"); }
    finally { setLoading(false); }
  };

  const handleExportPDF = async () => {
    try {
      const { pdf_url } = await signBatchExport(batch.id);
      if (pdf_url) {
        window.open(pdf_url, '_blank');
      } else {
        const res = await getBatchCodes(batch.id, { status: 'active', page_size: 100 });
        exportBatchPDF({ ...batch, codes: res.data });
      }
    } catch { toast.error("Failed to generate export link"); }
  };

  const handleExportCSV = async () => {
    try {
      const { excel_url } = await signBatchExport(batch.id);
      if (excel_url) {
        window.open(excel_url, '_blank');
      } else {
        const res = await getBatchCodes(batch.id, { status: 'active', page_size: 100 });
        exportBatchCSV({ ...batch, codes: res.data });
      }
    } catch { toast.error("Failed to generate export link"); }
  };

  const handleCancelCode = () => {
    if (!confirmCode) return;
    setVisibleCodes((prev) =>
      prev.map((c) => c.id === confirmCode.id ? { ...c, status: "cancelled" as const } : c)
    );
    toast.success(`Code ${confirmCode.code} cancelled`);
    setConfirmCode(null);
  };

  const progress = batch.quantity > 0 ? (batch.redeemed_count / batch.quantity) * 100 : 0;

  return (
    <>
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-wrap items-center gap-4 justify-between">
            <div className="space-y-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                {!hideCampaignName && <Link to={`/mpromo/campaigns/${batch.campaign_id}`} className="font-semibold text-sm hover:underline">{batch.campaign_name}</Link>}
                {hideCampaignName && <span className="font-semibold text-sm">Batch #{batch.id}</span>}
                {scopeMode === "all" && <TeamBadge teamName={batch.team_name} />}
              </div>
              <div className="text-xs text-muted-foreground flex flex-wrap gap-x-4 gap-y-1">
                <span>Generated {batch.created_at}</span>
                <span>by {batch.generated_by_name}</span>
              </div>
            </div>
            <div className="flex items-center gap-6 text-sm">
              <div className="text-center">
                <div className="font-semibold">{batch.quantity}</div>
                <div className="text-xs text-muted-foreground">codes</div>
              </div>
              <div className="text-center">
                <div className="font-semibold">GH₵{batch.redemption_amount.toLocaleString()}</div>
                <div className="text-xs text-muted-foreground">per code</div>
              </div>
              <div className="text-center">
                <div className="font-semibold">{batch.expires_at}</div>
                <div className="text-xs text-muted-foreground">expires</div>
              </div>
            </div>
          </div>
          <div className="mt-3 flex items-center gap-3">
            <Progress value={progress} className="flex-1 h-2" />
            <span className="text-xs text-muted-foreground whitespace-nowrap">
              {batch.redeemed_count} redeemed · {batch.active_count} active / {batch.quantity}
            </span>
          </div>
          <div className="mt-3 flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handleToggle} disabled={loading} className="gap-1.5">
              {loading ? "Loading..." : expanded ? <><ChevronUp className="h-4 w-4" /> Hide Codes</> : <><ChevronDown className="h-4 w-4" /> View Codes</>}
            </Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm" className="gap-1.5">
                  <Download className="h-4 w-4" /> Export
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem onClick={handleExportPDF}>
                  <Printer className="h-4 w-4 mr-2" /> Download PDF
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleExportCSV}>
                  <FileSpreadsheet className="h-4 w-4 mr-2" /> Download Excel
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          {expanded && (
            <>
              <BatchCodeTable codes={visibleCodes} canCancel={canCancel} onCancel={setConfirmCode} />
              {codesPage < codesLastPage && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="w-full mt-2 text-xs"
                  onClick={handleLoadMore}
                  disabled={loading}
                >
                  {loading ? 'Loading...' : `Load more (${visibleCodes.length} of ${codesTotal})`}
                </Button>
              )}
            </>
          )}
        </CardContent>
      </Card>

      <ConfirmDialog
        open={!!confirmCode}
        onOpenChange={(open) => { if (!open) setConfirmCode(null); }}
        title="Cancel Promo Code"
        description={`Are you sure you want to cancel code "${confirmCode?.code}"? This action cannot be undone.`}
        confirmLabel="Cancel Code"
        variant="destructive"
        onConfirm={handleCancelCode}
      />
    </>
  );
}
